# 37. Running a single job or Workflow at a Time Using Concurrency (3)
name: concurrency 1
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                type: environment
concurrency: 
    group: concurrency-1
    cancel-in-progress: true

jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 30