name: concurrency 2
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                type: environment

jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 30