name: Repository Events
on:
  push: # Run on every push to any branch
  pull_request:
    types: [opened, synchronize, reopened, synchronize] # Run on PR open, sync, reopen, close
  issues: # Run on issue open, close, reopen
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
      - uses: actions/checkout@v4