name: External Events
on:
    repository_dispatch:
        types: [build-to-test]

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo "Repository Dispatch event received!"
