name: Manually Triggered
on: 
    workflow_dispatch:
        inputs:
            string:
                description: A String Input
                type: string
                required: true
                default: "Default Val"
            number:
                description: A Number Input
                type: number
                required: true
                default: 1
            otption:
                description: A Option Input
                type: choice
                required: true
                options:
                    - "Option 1"
                    - "Option 2"
                    - "Option 3"
                    - "Option 4"
                default: "Option 1"
            boolean:
                description: A Boolean Input
                type: boolean
                required: true
                default: true
            environment:
                description: A Environment Input
                type: environment
                required: true
                default: "ENVIRONMENT"
            

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: echo $GITHUB_SHA
            - run: "String Input: ${{ inputs.string }}"
            - run: "Number Input: ${{ inputs.number }}"
            - run: "Option Input: ${{ inputs.option }}"
            - run: "Boolean Input: ${{ inputs.boolean }}"
            - run: "Environment Input: ${{ inputs.environment }}"
