# 35. Handling Failing Jobs in a Matrix (1)
name: Matrix
on: [push]


# Existing Combinations
# { X os: ubuntu-latest, node-version: 14}
# { Y os: ubuntu-latest, node-version: 15}
# { Y os: ubuntu-latest, node-version: 16}
# { X os: windows-latest, node-version: 14}
# { Y os: windows-latest, node-version: 15}
# { Y os: windows-latest, node-version: 16}

# Altered Combinations
# { X os: ubuntu-latest,  node-version: 14, is-ubuntu: true, experimental: false}
# { Y os: ubuntu-latest,  node-version: 15, is-ubuntu: true, experimental: false}
# { Y os: ubuntu-latest,  node-version: 16, is-ubuntu: true, experimental: true }
# { X os: windows-latest, node-version: 14,                  experimental: false}
# { Y os: windows-latest, node-version: 15,                  experimental: false}
# { Y os: windows-latest, node-version: 16,                  experimental: false}

# Added Cobminations
# { Y os: macos-latest ,  node-version: 15}
# { Y os: windows-latest, node-version: 17}

jobs:
    node-matrix:
        continue-on-error: false
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14, 15, 16]
                include:
                    - os: ubuntu-latest
                      is-ubuntu: true
                    - os: macos-latest
                      node-version: 15
                    - experimental: false
                    - os: ubuntu-latest
                      node-version: 16
                      experimental: true
                    - os: ubuntu-latest
                      node-version: 17
                exclude:
                  - os: ubuntu-latest
                    node-version: 14
            fail-fast: true
            # max-parallel: 3
        runs-on: ${{ matrix.os }}
        steps:
            - if: matrix.experimental == true
              run: exit 1
            - run: node -v
            - run: echo '${{ toJson(matrix) }}'
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v
     
             
       