# 30. Encrypting and Decrypting Large files in a Workflow (3) 
name: Variables and Secrets
on: [push]

jobs:
    decrypt-file:
        runs-on: ${{ vars.JOBS_RUNNER }}
        steps:
            - uses: actions/checkout@v3
            - name: Decrypt file
              env:
                PASSPHRASE: ${{ secrets.PASSPHRASE }}
              run: |
                  mkdir $HOME/secrets
                  echo ls
                  gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json secret.json.gpg
                  
            - name: View Encrypted File Content (NEVER DO THIS IN A WORKFLOW)
              run: |
                  cat secrets.txt
    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        environment: "staging"
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        steps:
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              
              run: |
                  echo '${{ vars.JOBS_RUNNER }}'
                  echo "ENV_LEVEL_VAR : $ENV_LEVEL_VAR"
                  echo "REPO_LEVEL_VAR : $REPO_LEVEL_VAR"
                  



